### PR TITLE
Add pyyaml dependency

### PR DESCRIPTION
**Pull request by tripleee**
Undeclared dependency

### CODE REVIEW

**Comment by sjlongland** [comment]
Ahh whoops, good catch. :-)

**Comment by tripleee** [comment]
Thanks for the quick response! The merge looks kind of funny, though; I could not simply merge your master with mine. Is there something I should configure differently in order to be able to sync back without manual intervention?

**Comment by sjlongland** [comment]
Yeah, I did a rebase-merge, so your commit looks like it's on top.  It should be safe enough to pull master and it should just "fast forward" to the merge-commit. :-)

**Comment by tripleee** [comment]
Sure, just making sure I am not doing something wrong. Do you do rebase as a matter of course?

**Comment by sjlongland** [comment]
Pretty much… it makes the commit history more linear, which is what I understand to be the intent of git.  Least that's what I see with its use in the Linux kernel environment where git came from. :-)

**Pull request merged**
